services:
    Felds\TusServerBundle\Entity\UploadManager:
        public: true
        arguments:
            $class: '%felds_tus_server.entity_class%'
            $expiresIn: '%felds_tus_server.expires_in%'
            $maxSize: '%felds_tus_server.max_size%'
            $em: '@Doctrine\ORM\EntityManagerInterface' #TODO customize connection

    Felds\TusServerBundle\Controller\:
        autowire: true
        resource: '../../Controller'
        tags: ['controller.service_arguments']
